version: "3.7"

services:
  database_concessionaria:
    image: postgres
    container_name: database_concessionaria
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=concessionaria
    volumes:
      - postgres:/data/postgres

  app:
    build: .
    container_name: concessionaria-api
    ports:
      - "3333:3333"
    depends_on:
      - database_concessionaria
    environment:
      - DB_HOST=database_concessionaria
      - DB_PORT=5432
      - DB_USERNAME=admin
      - DB_PASSWORD=admin
      - DB_NAME=concessionaria

volumes:
  postgres:
    driver: local