services:
  app:
    build: .
    ports:
      - "3333:3333"
    environment:
      - DB_PORT=5432
      - DB_HOST=db
      - DB_USERNAME=postgres
      - DB_PASSWORD=marvinx
      - DB_NAME=postgres
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    command: yarn start

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=marvinx
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    driver: local
