version: "3.7"

services:
  database_concessionaria:
    image: postgres
    container_name: database_concessionaria
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=concessionaria
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: concessionaria-api
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/app
    depends_on:
      - database_concessionaria

volumes:
  pgdata:
    driver: local